HT-2958: Generate list of institution names + entity IDs
hathitrust/crms pull request #58
Opened 2021-05-26 22:00 UTC by aelkiss

I needed to generate a list of institution names + entity IDs for use by HTRC's new functionality to log in via HathiTrust. Since we're already generating the institution names + inst ids here, this seemed like a reasonable place to do it.

2021-05-27 14:48 UTC, moseshll requested changes
Please also bump the version number in cgi/CRMS.pm line 60. I'd love to find an automated way to get version numbers into the codebase (version number is displayed in the HTML header, so we need it somewhere) but never came up with a decent mechanism. It's a PITA that has bitten me in the behind many times.

2021-05-28 12:21 UTC, aelkiss commented
Version updated & force pushed.

2021-05-28 16:55 UTC, moseshll approved these changes

2021-05-28 16:55 UTC, merged

2021-05-28 17:18 UTC, aelkiss commented
@moseshll  Please feel free to deploy this at your convenience -- I'm also happy to do so assuming it uses the stage-app / deploy-app scripts.